#!/bin/bash -l

# Specify the project and resource allocation
#$ -P tianlabdl
#$ -l h_rt=1:00:00
#$ -j y
#$ -t 1-20  # Array job: 20 tasks/nodes

# Load the required Python module and activate the virtual environment
module load python3/3.10.12
source .venv/bin/activate

# Run Python script to init sweep and print id, capture that id (last line - tail)
id=$(python3 sweep.py | tail -n 1)

# Start sweep with agent with previously captured id
wandb agent --count 1 cisl-bu/sweep_example/$id
